---
- hosts: all
  tasks:
    - name: Install build-essential
      apt: name=build-essential
      become: true
    - name: Install Python 2/3
      apt:
        pkg:
          - python
          - python-pip
          - python3
          - python3-pip
          - pandoc
      become: true
    - name: Install Java
      apt:
        pkg:
          - default-jdk
      become: true
    - name: Install Maven
      import_tasks: core-tasks/maven.yml
    - name: Install Docker
      import_tasks: core-tasks/docker.yml
    - name: Install GoLang
      import_tasks: core-tasks/golang.yml
    - name: Install NodeJS
      import_tasks: core-tasks/nodejs.yml
    - name: Install Nix
      import_tasks: core-tasks/nix.yml
    - name: Install Radare2
      import_tasks: core-tasks/radare2.yml
